### ISSUE TITLE
BUG-updating an entity properties removes the label ?

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-core#703] opened 2023-07-25 09:12 UTC
**Description**
After creating a scenario, if we update the properties, the label is lost

**How to reproduce**

    ```
    import taipy as tp;
    ...
    scenario = tp.create_scenario(a_config, a_date, "a label")
    with scenario as sc:
        sc.properties.update(dict())
    ```

**Expected behavior**
the label should be "a label" but it is a_config.id

**Comment by toan-quach** [comment] 2023-07-25 11:48
Hi @FredLL-Avaiga I tried to add some code to yours to reproduce the problem. But I can't reproduce it 😅 let me know if I did anything wrong

```
from datetime import datetime

import taipy as tp
from taipy.config import Config

scenario_config = Config.configure_scenario("scenario", [])

scenario = tp.create_scenario(scenario_config, datetime.now(), "a label")
print(scenario._properties)     # {'name': 'a label'}
print(scenario.properties)     # {'name': 'a label'}
print(scenario.name)     # a label

with scenario as sc:
    sc.properties.update(dict())
    print(sc._properties)     # {'name': 'a label'}
    print(sc.properties)     # {'name': 'a label'}
    print(sc.name)     # a label

print(scenario._properties)     # {'name': 'a label'}
print(scenario.properties)     # {'name': 'a label'}
print(scenario.name)     # a label
```

**Comment by FredLL-Avaiga** [comment] 2023-07-25 11:52
Did you try outside of the context manager?

**Comment by toan-quach** [comment] 2023-07-25 11:54
Yep I also just edited the output above.

**Comment by toan-quach** [comment] 2023-07-25 11:57
Ahhg I was using `taipy-core==2.3.1`!!
I just reinstalled develop and you're right!!! Here is the result:

```
from datetime import datetime

import taipy as tp
from taipy.config import Config

scenario_config = Config.configure_scenario("scenario", [])

scenario = tp.create_scenario(scenario_config, datetime.now(), "a label")
print(scenario._properties)     # {'name': 'a label'}
print(scenario.properties)     # {'name': 'a label'}
print(scenario.name)     # a label

with scenario as sc:
    sc.properties.update(dict())
    print(sc._properties)     # {'name': 'a label'}
    print(sc.properties)     # {'name': 'a label'}
    print(sc.name)     # a label

print(scenario._properties)     # {}
print(scenario.properties)     # {}
print(scenario.name)     # None
```

**Comment by toan-quach** [comment] 2023-07-25 12:11
@FredLL-Avaiga
This problem will be fixed in this PR: https://github.com/Avaiga/taipy-core/pull/704

**Comment by FredLL-Avaiga** [comment] 2023-07-25 12:14
👌

**Comment by toan-quach** [comment] 2023-07-25 12:17
@jrobinAV @FredLL-Avaiga 

This problem only occurs in develop branch and it's a bug that was created from this PR https://github.com/Avaiga/taipy-core/pull/654/files#diff-1a0ebff84b109abe19d66040dc7bf6c03c9bd446972fa74e4b79a9155e691a8f

When in context manager, we create a dictionary `_pending_change` to postpone the changes to the properties until we exit the context manager (we then replace the value (by setting) in properties with the value in `_pending_changes`. By calling `properties.update(dict())`, we set the _pending_changes` to an empty dict and because we're setting `_pending_changes` instead of calling update() to the values in properties, the dict() overrides all of the value in properties.

This changes only apply to `develop` branch and 2.3 is fine. So I'll be removing the 2.4 tag in the Release :D

**Comment by toan-quach** [comment] 2023-07-27 08:56
Hi @FredLL-Avaiga 
The PR https://github.com/Avaiga/taipy-core/pull/704 has been merged. Can you pull and test again? Thanks!

PS: deleting item in properties is also implemented in this PR. You can test it too :D

**Comment by jrobinAV** [comment] 2023-07-27 09:01
Can you also backport the fix in `dev/2.4` and `release/2.3` branches?

**Comment by toan-quach** [comment] 2023-07-27 09:05
@jrobinAV 
2.3 and 2.4 actually don't have this problem 😃 you can refer to my explanation above (https://github.com/Avaiga/taipy-core/issues/703#issuecomment-1649728716). So I believe backporting to 2.3 and 2.4 won't be necessary 😃

**Comment by FredLL-Avaiga** [comment] 2023-07-27 09:16
> Hi @FredLL-Avaiga The PR #704 has been merged. Can you pull and test again? Thanks!
> 
> PS: deleting item in properties is also implemented in this PR. You can test it too :D

I will, tx @toan-quach

**Comment by FredLL-Avaiga** [comment] 2023-07-27 09:32
I can confirm that the name is preserved when updating the properties with an empty dict

**Comment by FredLL-Avaiga** [comment] 2023-07-27 09:33
And I can also delete and rename properties

Great job 🥇

**Closed as completed** 2023-07-31 09:11 UTC
